### PR TITLE
Fix S1615 min and max

### LINKED ISSUE #10: Maximum and minimum values incorrect for S1615
The minimum and maximum values of the S1615 are related to 2^15 rather than 2^16.  This should be corrected.

### PR DESCRIPTION
**Pull request by rowleya**
Fixed #10

### CODE REVIEW

**Comment by dkfellows** [comment]
Looks good

**Comment by dkfellows** [comment]
I think you will find that `65535.99996948242`provides sufficient precision for the max.

**Comment by rowleya** [comment]
The number I used is simply (2^31 - 1) / 32768, which is exactly the value of the 32-bit s1615 fixed-point number with all 1s except the first (sign) bit.  I did this with the Windows calculator, so if you get a different result doing the same on a more accurate system, this can be changed of course.

**Comment by dkfellows** [comment]
That was the value I was using too, but the Windows calculator doesn't use a minimal number of digits. (The algorithm to generate a minimal number of digits that, when parsed to a `double`, produce an exact binary representation, that algorithm is _deeply evil_ and well into Dave-level numerics hackery. This is why I'm not fazed by much of the code in spinn_common…)

**Comment by rowleya** [comment]
Ahh OK, you were looking at the double value of that number... I had forgotten about that part of the representation.  I guess that Decimal does this for us, but I don't know for sure.

**Comment by alan-stokes** [comment]
ready for merge then or are you wanting to lose the last 4 numbers?

**Comment by rowleya** [comment]
I doubt a difference of 4 numbers matters - I would say merge!

**Pull request merged**
